network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256
  imgH: 64
  lang_list:
    - en
  character_list: 0123456789
  number: '0123456789'
  symbol: ''
  lang_char: ''
  experiment_name: cryptogram_digits
  train_data: all_data
  valid_data: all_data/val
  manualSeed: 1111
  workers: 4
  batch_size: 32
  num_iter: 5000
  valInterval: 100
  saved_model: saved_models/english_g2.pth
  FT: true
  optim: adam
  lr: 0.0001
  beta1: 0.9
  rho: 0.95
  eps: 1.0e-08
  grad_clip: 5
  select_data: train
  batch_ratio: '1'
  total_data_usage_ratio: 1.0
  batch_max_length: 2
  imgW: 200
  rgb: false
  contrast_adjust: false
  sensitive: true
  PAD: true
  data_filtering_off: false
  Transformation: None
  FeatureExtraction: VGG
  SequenceModeling: BiLSTM
  Prediction: CTC
  num_fiducial: 20
  decode: greedy
  new_prediction: false
  freeze_FeatureFxtraction: false
  freeze_SequenceModeling: false
